### ISSUE TITLE
Grun.Net does not seem to work with Antlr4.Runtime.Standard

### ISSUE THREAD

**Issue by kaby76** [wiredwiz/Grun.Net#31]
Grun.Net does not seem to work with a net472 assembly built against [Antlr4.Runtime.Standard v4.8](https://www.nuget.org/packages/Antlr4.Runtime.Standard/). At assembly.GetTypes(), line 83, Scanner.c "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information" Note: [Antlr4cs](https://www.nuget.org/packages/Antlr4/) is several versions behind the current Antlr code base, now 4.8. Version 4.6.6 in the Antlr4 code tree was last updated a year ago, but forked from 4.6, which was released in 2016! 4.7 was released in 2017. 4.8 was released a few months ago. The Antlr4cs code hasn't been updated by Harwell for over a year, and unclear if he is maintaining that codebase now. Other than that and a few minor problems (lexer error messages are not displayed, selection of input or tokens not reflected in selection in tree), the code works well.

**Comment by wiredwiz** [comment]
Thank you for bringing this to my attention.  I will add it to my to-do list and begin looking into it now.  As far as selecting nodes in the tree goes, that is problematic.  Strangely, Microsoft did not supply a public method for selecting a node in the tree graph.  I wish they had.  My only option if I want to implement that is to do a fork of their source code with a slight modification and thus far I haven't felt that functionality was worth going that route.  I can certainly make lexer errors available.  I will add that to the list.

**Comment by wiredwiz** [comment]
Just to be clear, I started learning anything substantial about ANTLR about 6 weeks ago, so I'm not well versed on most of the internals.  I know enough to be dangerous and I can reverse engineer well.  As a result, my learning curve on a lot of this is a bit steep.

**Comment by wiredwiz** [comment]
I have now released Grun.Net 2.0.23321.1 that targets support of the standard runtime.  The previous 1.x versions still target the old runtime.  In the future I plan to refactor the project design heavily to abstract all the dependencies on the runtime libraries making it possible to support both in a 3.x version of the tool.
